name: Basic GA

on: [push, workflow_dispatch]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  nodejssetup:
    name: Nodejs setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo "Node version successfully installed"
