name: Basic GA

on: [push, workflow_dispatch]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: yarn install
      - run: yarn test


  setup:
    needs: tests
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo "Node version successfully installed"
      - run: yarn install
      - run: yarn run build


