name: Basic GA

on: [push, workflow_dispatch]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo "Node version successfully installed"
      - run: yarn install
      - run: yarn run build

  tests:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: yarn install
      - run: yarn test
